### ISSUE TITLE
Stack loading in reverse

### ISSUE THREAD

**Issue by GreatOwl** [quickenloans-mcp/mcp-panthor#14]
Chris F pointed out to me something that is probably a bug, his controller is run correctly, but his stack is run in the reverse order.  I am still debugging it and will issue a PR if I solve it, but it looks like its related to the way this works:
[array_pop](https://github.com/quickenloans-mcp/mcp-panthor/blob/master/src/Bootstrap/RouteLoader.php#L117) and [foreach](https://github.com/quickenloans-mcp/mcp-panthor/blob/master/src/Bootstrap/RouteLoader.php#L122) while traversing the array.

array_pop takes the last thing added to the array (the controller) where foreach starts from the first thing in the stack (0). For each reads our routes in the correct order, but Slim's route handling runs middleware in the opposite order they are added... that is the last added is the first run.

For example if your array stack looked like this:

```yaml
    route:
        stack:
            - auth
            - loader
            - processor
            - controller
```
the order it would run in is:
- processor
- loader
- auth
- controller

Pull request to fix this coming shortly
